Legacy/config/routes.rb
Themathist::Application.routes.draw do

  #the app route
  get '/app' => 'client#app'

  #admin
  namespace :admin do
    get '/' => 'pages#index'
    resources :feedbacks
    resources :updates
    resources :users
    resources :settings
  end

  #root
  root :to => 'client#index'

  #client routes
  post   'client/new_session'     => 'client#new_session'
  post   'client/save_config'     => 'client#save_config'
  get    'client/log_out'         => 'client#log_out'
  get    'client/updates'         => 'client#get_updates'
  post   'client/send_feedback'   => 'client#send_feedback'
  post   'client/log'             => 'client#log'
  post   'client/calculate'       => 'client#calculate'
  post   'client/images/download' => 'client#download_image'
  post   'client/images/upload'   => 'client#upload_image'
  post   'client/geogebra/search' => 'client#search_geogebra'
  get    'client/images/:hash'    => 'client#load_image'
  delete 'client/user'            => 'client#delete_user'

  get 'open' => 'client#open_drive_file'
end

Legacy/app/models/setting.rb
class Setting < ActiveRecord::Base
  validates_presence_of :key, :value

  def self.get key
    setting = Setting.where(key: key).first
    if setting.present?
      JSON.parse setting.value
    else
      nil
    end
  end

  def self.get_single_value key
    json = get key
    if json.present?
      json['value']
    else
      nil
    end
  end

  def self.set key, value
    setting = Setting.where(key: key).first
    if setting.present?
      setting.value = value
      setting.save
    else
      setting = Setting.create(key: key, value: value)
    end
    setting
  end

  def self.set_single_value key, value
    set key, {value: value}.to_json
  end
end

Legacy/app/controllers/admin/settings_controller.rb
class Admin::SettingsController < Admin::BaseController
  before_action :set_setting, only: [:show, :edit, :update, :destroy]

  # GET /admin/settings
  def index
    @settings = Setting.all
  end

  # GET /admin/settings/1
  def show
  end

  # GET /admin/settings/new
  def new
    @setting = Setting.new
  end

  # GET /admin/settings/1/edit
  def edit
  end

  # POST /admin/settings
  def create
    @setting = Setting.new(setting_params)

    if @setting.save
      redirect_to [:admin, @setting], notice: 'Setting was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /admin/settings/1
  def update
    if @setting.update(setting_params)
      redirect_to admin_settings_url, notice: 'Setting was successfully settingd.'
    else
      render action: 'edit'
    end
  end

  # DELETE /admin/settings/1
  def destroy
    @setting.destroy
    redirect_to admin_settings_url, notice: 'Setting was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def setting_params
      params.require(:setting).permit(:key, :value)
    end
end

Legacy/app/views/admin/settings/_form.html.erb
<%= form_for [:admin, @setting] do |f| %>
  <% if @setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% @setting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :key %><br>
    <%= f.text_field :key %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_area :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Legacy/app/views/admin/settings/edit.html.erb
<h1>Editing setting</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @setting] %> |
<%= link_to 'Back', admin_settings_path %>

Legacy/app/views/admin/settings/index.html.erb
<h1>Listing Settings</h1>

<table>
  <thead>
    <tr>
      <th>Key</th>
      <th>Value</th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= setting.key %></td>
        <td><%= setting.value %></td>
        <td><%= link_to 'Edit', edit_admin_setting_path(setting) %></td>
      </tr>
    <% end %>
  </tbody>
</table>