Legacy/config/routes.rb
Themathist::Application.routes.draw do

  #the app route
  get '/app' => 'client#app'

  #admin
  namespace :admin do
    get '/' => 'pages#index'
    resources :feedbacks
    resources :updates
    resources :users
    resources :settings
  end

  #root
  root :to => 'client#index'

  #client routes
  post   'client/new_session'     => 'client#new_session'
  post   'client/save_config'     => 'client#save_config'
  get    'client/log_out'         => 'client#log_out'
  get    'client/updates'         => 'client#get_updates'
  post   'client/send_feedback'   => 'client#send_feedback'
  post   'client/log'             => 'client#log'
  post   'client/calculate'       => 'client#calculate'
  post   'client/images/download' => 'client#download_image'
  post   'client/images/upload'   => 'client#upload_image'
  post   'client/geogebra/search' => 'client#search_geogebra'
  get    'client/images/:hash'    => 'client#load_image'
  delete 'client/user'            => 'client#delete_user'

  get 'open' => 'client#open_drive_file'
end

Legacy/app/models/feedback.rb
class Feedback < ActiveRecord::Base
    belongs_to :user
end

Legacy/app/controllers/admin/feedbacks_controller.rb
class Admin::FeedbacksController < Admin::BaseController
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]

  # GET /admin/feedbacks
  def index
    @feedbacks = Feedback.all
  end

  # GET /admin/feedbacks/1
  def show
  end

  # GET /admin/feedbacks/1/edit
  def edit
  end

  # PATCH/PUT /admin/feedbacks/1
  def update
    if @feedback.update(feedback_params)
      redirect_to [:admin, @feedback], notice: 'Feedback was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /admin/feedbacks/1
  def destroy
    @feedback.destroy
    redirect_to admin_feedbacks_url, notice: 'Feedback was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def feedback_params
      params.require(:feedback).permit(:user_id, :content)
    end
end

Legacy/app/views/admin/feedbacks/edit.html.erb
<h1>Editing feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @feedback] %> |
<%= link_to 'Back', admin_feedbacks_path %>

Legacy/app/views/admin/feedbacks/index.html.erb
<h1>Listing feedbacks</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Content</th>
      <th>Date</th>
    </tr>
  </thead>

  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td>
          <% if feedback.user %>
            <%= feedback.user.name %> </br> <i><%= feedback.user.mail %></i>
          <% else %>-<% end %>
        </td>
        <td><%= feedback.content %></td>
        <td><%= feedback.created_at %></td>
        <td><%= button_to "delete", [:admin, feedback], :method=>:delete%></td>
      </tr>
    <% end %>
  </tbody>
</table>

Legacy/app/views/admin/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @feedback.user_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @feedback.content %>
</p>

<%= link_to 'Edit', edit_admin_feedback_path(@feedback) %> |
<%= link_to 'Back', admin_feedbacks_path %>