Legacy/config/routes.rb
Themathist::Application.routes.draw do

  #the app route
  get '/app' => 'client#app'

  #admin
  namespace :admin do
    get '/' => 'pages#index'
    resources :feedbacks
    resources :updates
    resources :users
    resources :settings
  end

  #root
  root :to => 'client#index'

  #client routes
  post   'client/new_session'     => 'client#new_session'
  post   'client/save_config'     => 'client#save_config'
  get    'client/log_out'         => 'client#log_out'
  get    'client/updates'         => 'client#get_updates'
  post   'client/send_feedback'   => 'client#send_feedback'
  post   'client/log'             => 'client#log'
  post   'client/calculate'       => 'client#calculate'
  post   'client/images/download' => 'client#download_image'
  post   'client/images/upload'   => 'client#upload_image'
  post   'client/geogebra/search' => 'client#search_geogebra'
  get    'client/images/:hash'    => 'client#load_image'
  delete 'client/user'            => 'client#delete_user'

  get 'open' => 'client#open_drive_file'
end

Legacy/app/models/user.rb
class User < ActiveRecord::Base
    has_many :feedbacks
    has_many :demo_requests, inverse_of: :user

    after_create :send_welcome_email

    def send_welcome_email
        UserMailer.welcome_email(self).deliver_later
    end
end

Legacy/app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_users, only: [:index]

  # GET /admin/users
  def index
  end

  # GET /admin/users/1
  def show
  end

  # GET /admin/users/new
  def new
    @user = User.new
  end

  # GET /admin/users/1/edit
  def edit
  end

  # POST /admin/users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to [:admin, @user], notice: 'User was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /admin/users/1
  def update
    if @user.update(user_params)
      redirect_to [:admin, @user], notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /admin/users/1
  def destroy
    @user.destroy
    redirect_to admin_users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:id, :mail, :name, :premium, :points, :config, :last_login, :login_count, :provider, :user_id)
    end

    def set_users
      @users = User.order(login_count: :desc, last_login: :desc)

      limit  = params[:limit] ? params[:limit] : 10
      @users = @users.limit(limit)

      offset = params[:offset]
      @users = @users.offset(offset) if offset
    end
end

Legacy/app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :mail %><br>
    <%= f.text_field :mail %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :premium %><br>
    <%= f.number_field :premium %>
  </div>
  <div class="field">
    <%= f.label :config %><br>
    <%= f.text_field :config %>
  </div>
  <div class="field">
    <%= f.label :provider %><br>
    <%= f.number_field :provider %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Legacy/app/views/admin/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @user] %> |
<%= link_to 'Back', admin_users_path %>

Legacy/app/views/admin/users/index.csv.erb
First name, Email, Last login, Login count, Drive requests count
<% @users.each do |user| %>
<%= user.name %>, <%= user.mail %>, <%= user.last_login %>, <%= user.login_count %>, <%= user.drive_requests_count %>
<% end %>

Legacy/app/views/admin/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mail</th>
      <th>Last login</th>
      <th>Login count</th>
      <th>Drive requests count</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.mail %></td>
        <td><%= user.last_login %></td>
        <td><%= user.login_count %></td>
        <td><%= user.drive_requests_count %></td>
        <td><%= link_to 'Show', [:admin, user] %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
        <td><%= button_to "delete", [:admin, user], :method=>:delete%></td>
      </tr>
    <% end %>
  </tbody>
</table>

Legacy/app/views/admin/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

Legacy/app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Provider:</strong>
  <%=
    if @user.provider == 0 then
        'Google'
    else
        'Facebook'
    end
  %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @user.mail %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <img src="<%= @user.img %>">
</p>

<p>
  <strong>Premium:</strong>
  <%= @user.premium %>
</p>

<p>
  <strong>Config:</strong>
  <%= @user.config %>
</p>

<p>
  <strong>Last login:</strong>
  <%= @user.last_login %>
</p>


<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>