Legacy/config/routes.rb
Themathist::Application.routes.draw do

  #the app route
  get '/app' => 'client#app'

  #admin
  namespace :admin do
    get '/' => 'pages#index'
    resources :feedbacks
    resources :updates
    resources :users
    resources :settings
  end

  #root
  root :to => 'client#index'

  #client routes
  post   'client/new_session'     => 'client#new_session'
  post   'client/save_config'     => 'client#save_config'
  get    'client/log_out'         => 'client#log_out'
  get    'client/updates'         => 'client#get_updates'
  post   'client/send_feedback'   => 'client#send_feedback'
  post   'client/log'             => 'client#log'
  post   'client/calculate'       => 'client#calculate'
  post   'client/images/download' => 'client#download_image'
  post   'client/images/upload'   => 'client#upload_image'
  post   'client/geogebra/search' => 'client#search_geogebra'
  get    'client/images/:hash'    => 'client#load_image'
  delete 'client/user'            => 'client#delete_user'

  get 'open' => 'client#open_drive_file'
end

Legacy/app/models/update.rb
class Update < ActiveRecord::Base
    belongs_to :user
end

Legacy/app/controllers/admin/updates_controller.rb
class Admin::UpdatesController < Admin::BaseController
  before_action :set_update, only: [:show, :edit, :update, :destroy]

  # GET /admin/updates
  def index
    @updates = Update.all
  end

  # GET /admin/updates/1
  def show
  end

  # GET /admin/updates/new
  def new
    @update = Update.new
  end

  # GET /admin/updates/1/edit
  def edit
  end

  # POST /admin/updates
  def create
    @update = Update.new(update_params)

    if @update.save
      redirect_to [:admin, @update], notice: 'Update was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /admin/updates/1
  def update
    if @update.update(update_params)
      redirect_to @update, notice: 'Update was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /admin/updates/1
  def destroy
    @update.destroy
    redirect_to admin_updates_url, notice: 'Update was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_update
      @update = Update.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def update_params
      params.require(:update).permit(:user_id, :title, :content, :for_user)
    end
end

Legacy/app/views/admin/updates/_form.html.erb
<%= form_for [:admin, @update] do |f| %>
  <% if @update.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@update.errors.count, "error") %> prohibited this update from being saved:</h2>

      <ul>
      <% @update.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :for_user %><br>
    <%= f.number_field :for_user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Legacy/app/views/admin/updates/edit.html.erb
<h1>Editing update</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @update] %> |
<%= link_to 'Back', admin_updates_path %>

Legacy/app/views/admin/updates/index.html.erb
<h1>Listing updates</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Content</th>
      <th>For</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @updates.each do |update| %>
      <tr>
        <td><%= update.user_id %></td>
        <td><%= update.title %></td>
        <td><%= update.content %></td>
        <td><%= update.for_user %></td>
        <td><%= link_to 'Show', [:admin, update] %></td>
        <td><%= link_to 'Edit', edit_admin_update_path(update) %></td>
        <td><%= button_to "delete", [:admin, update], :method=>:delete%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Update', new_admin_update_path %>

Legacy/app/views/admin/updates/new.html.erb
<h1>New update</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_updates_path %>

Legacy/app/views/admin/updates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @update.user_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @update.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @update.content %>
</p>

<p>
  <strong>For:</strong>
  <%= @update.for_user %>
</p>

<%= link_to 'Edit', edit_admin_update_path(@update) %> |
<%= link_to 'Back', admin_updates_path %>